command name: void
permission: tralalal
disableitemdisappearing: false

texts:
  name: "Void                side " # name of the GUIs
  previous: "previous side" # name of the item that moves player to previous side
  next: "next side" # name of the item that moves player to next side

voidinv:
  oneInv: true # will all worlds have separate void inventory?
  exception: false # Works only if separate is true. Allows combining inv Guis with chosen worlds
  putIn: true # if players can move items inside the GUIs
  voidfall: true # if item that falls to void will be moved to gui

  combine:
    1:
      command: parapa # command to open the GUI
      permission: worldClear.blabla # 0 means disabled, everyone can execute it
      works: false # if the command will work in every world
      worlds: # list of worlds with the same GUI
        - nether
        - overworld
    2:
      command: parap
      permission: worldclear.blbalb
      works: true
      worlds:
        - spawn
        - overworld



