messages:
  on clearing world to players:
    "&7You dont have permission to use this plugin"
  on empty inv:
    "Otchłan jest pusta"

time between clears: # in seconds
  20

on: #if automatic clearing will be enabled on start
  false